#!/usr/bin/env python3
"""arch-check scanner para el repo informegmf.

Audita tres reglas:
  1. Max 200 lineas por archivo .ts/.tsx/.js/.jsx en src/ y backend/src/
  2. Sin SQL hardcodeado en TS/JS (queries deben vivir en .sql separados)
  3. Sin URLs ni emails de SA hardcodeados en TS/JS (deben venir de config)

Salida: reporte markdown a stdout. Exit code 0 si OK, 1 si hay violaciones.
"""

import re
import sys
from pathlib import Path

MAX_LINES = 200
SCAN_DIRS = ("src", "backend/src")
CODE_EXTS = {".ts", ".tsx", ".js", ".jsx"}

EXEMPT_PATHS = {
    "src/integrations/supabase/types.ts",
    "src/integrations/supabase/client.ts",
}
EXEMPT_REGEX = (
    r"node_modules/",
    r"dist/",
    r"\.next/",
    r"\.gen\.(ts|tsx|js|jsx)$",
)
AUTOGEN_BANNERS = (
    "// auto-generated",
    "// This file is auto-generated",
    "// This file is automatically generated",
)

URL_ALLOWLIST = (
    "https://accounts.google.com",
    "https://www.googleapis.com/oauth2/v3/certs",
    "https://oauth2.googleapis.com/token",
    "https://storage.googleapis.com",
    "https://bigquery.googleapis.com",
)

SQL_KEYWORDS = re.compile(
    r"\b(SELECT|INSERT\s+INTO|UPDATE\s+\w+\s+SET|DELETE\s+FROM|"
    r"CREATE\s+(TABLE|INDEX|POLICY|FUNCTION|TRIGGER|VIEW)|"
    r"WITH\s+\w+\s+AS\b|JOIN\s+|"
    r"COUNTIF\(|GROUP\s+BY|ORDER\s+BY|HAVING\s+)\b",
    re.IGNORECASE,
)
SQL_FROM = re.compile(r"\bFROM\s+[`\"'\\]", re.IGNORECASE)
URL_PATTERN = re.compile(r"https?://[a-zA-Z0-9._/\-]+")
SA_EMAIL_PATTERN = re.compile(r"[a-zA-Z0-9._-]+@[a-zA-Z0-9._-]+\.iam\.gserviceaccount\.com")


def find_repo_root(start: Path) -> Path:
    p = start.resolve()
    while p != p.parent:
        if (p / ".git").is_dir():
            return p
        p = p.parent
    raise SystemExit("repo root not found (no .git up the tree)")


def is_exempt(rel: str, content: str) -> bool:
    if rel in EXEMPT_PATHS:
        return True
    for pat in EXEMPT_REGEX:
        if re.search(pat, rel):
            return True
    head = content[:200]
    return any(banner in head for banner in AUTOGEN_BANNERS)


def strip_comments(content: str) -> str:
    """Remove // line comments and /* block */ comments. Strings are preserved."""
    content = re.sub(r"/\*[\s\S]*?\*/", "", content)
    content = re.sub(r"//.*?$", "", content, flags=re.MULTILINE)
    return content


def detect_sql(content: str) -> list:
    """Find SQL queries inside template literals (backticks).

    Returns list of (line_no, snippet)."""
    no_comments = strip_comments(content)
    lines = no_comments.split("\n")
    violations = []
    in_template = False
    buf = []
    start_line = 0

    for i, raw in enumerate(lines, start=1):
        idx = 0
        while idx < len(raw):
            tick = raw.find("`", idx)
            if tick == -1:
                if in_template:
                    buf.append(raw[idx:])
                break
            if not in_template:
                in_template = True
                start_line = i
                buf = []
                idx = tick + 1
            else:
                buf.append(raw[idx:tick])
                joined = "\n".join(buf)
                if SQL_KEYWORDS.search(joined) and SQL_FROM.search(joined):
                    snippet = " ".join(joined.split())[:80]
                    violations.append((start_line, snippet))
                in_template = False
                buf = []
                idx = tick + 1
    return violations


def detect_hardcoded(content: str) -> list:
    """Find hardcoded URLs and SA emails outside comments and outside the allowlist."""
    no_comments = strip_comments(content)
    out = []
    for i, line in enumerate(no_comments.split("\n"), start=1):
        for m in URL_PATTERN.finditer(line):
            url = m.group(0)
            if any(url.startswith(a) for a in URL_ALLOWLIST):
                continue
            out.append((i, "URL", url))
        for m in SA_EMAIL_PATTERN.finditer(line):
            out.append((i, "SA email", m.group(0)))
    return out


def main():
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8")
    repo = find_repo_root(Path.cwd())
    over_size = []
    sql_in_code = []
    hardcoded = []

    for d in SCAN_DIRS:
        base = repo / d
        if not base.exists():
            continue
        for path in base.rglob("*"):
            if not path.is_file() or path.suffix not in CODE_EXTS:
                continue
            try:
                content = path.read_text(encoding="utf-8")
            except UnicodeDecodeError:
                continue
            rel = path.relative_to(repo).as_posix()
            if is_exempt(rel, content):
                continue
            line_count = content.count("\n") + (0 if content.endswith("\n") else 1)
            if line_count > MAX_LINES:
                over_size.append((rel, line_count))
            for line_no, snippet in detect_sql(content):
                sql_in_code.append((rel, line_no, snippet))
            for line_no, kind, value in detect_hardcoded(content):
                hardcoded.append((rel, line_no, kind, value))

    print("# arch-check report\n")
    print(f"Repo root: `{repo.as_posix()}`\n")

    print("## Regla 1: máximo 200 líneas por archivo")
    if not over_size:
        print("OK: Todos los archivos OK\n")
    else:
        print(f"FAIL: {len(over_size)} archivos sobrepasan {MAX_LINES} líneas:\n")
        print("| archivo | líneas | exceso |")
        print("|---|---:|---:|")
        for rel, n in sorted(over_size, key=lambda x: -x[1]):
            print(f"| `{rel}` | {n} | +{n - MAX_LINES} |")
        print()

    print("## Regla 2: sin SQL hardcodeado en TS/JS")
    if not sql_in_code:
        print("OK: No se detectó SQL en TS/JS\n")
    else:
        print(f"FAIL: {len(sql_in_code)} ocurrencias de SQL en código:\n")
        print("| archivo | línea | snippet |")
        print("|---|---:|---|")
        for rel, line_no, snippet in sql_in_code[:50]:
            esc = snippet.replace("|", "\\|")
            print(f"| `{rel}` | {line_no} | `{esc}…` |")
        if len(sql_in_code) > 50:
            print(f"\n…y {len(sql_in_code) - 50} más.")
        print()

    print("## Regla 3: sin URLs / SA emails hardcodeados en TS/JS")
    if not hardcoded:
        print("OK: Sin hardcoded\n")
    else:
        print(f"FAIL: {len(hardcoded)} ocurrencias:\n")
        print("| archivo | línea | tipo | valor |")
        print("|---|---:|---|---|")
        for rel, line_no, kind, value in hardcoded[:50]:
            print(f"| `{rel}` | {line_no} | {kind} | `{value}` |")
        if len(hardcoded) > 50:
            print(f"\n…y {len(hardcoded) - 50} más.")
        print()

    total = len(over_size) + len(sql_in_code) + len(hardcoded)
    print(f"## Total: **{total}** violaciones")
    sys.exit(1 if total > 0 else 0)


if __name__ == "__main__":
    main()
