SELECT DISTINCT UPPER(IFNULL(CAST(placa AS STRING),'')) AS value, CAST(descripcion AS STRING) AS extra
FROM `${TABLES_relatorio}`
WHERE ${COMITENTE_FILTER}
  AND ${ESTADO_ALLOWED_FILTER}
  AND IFNULL(CAST(placa AS STRING),'') != ''
  AND UPPER(IFNULL(CAST(placa AS STRING),'')) LIKE '%${qUpper}%'${ctxSQL}
ORDER BY value
LIMIT 20
